// Self-host the Google Fonts used on the site so visitor IPs never reach
// Google. This avoids the GDPR / LG München I (Az. 3 O 17493/20) issue
// around third-country transfers via Google Fonts' CDN.
//
// Run with `npm run fonts` after editing the FONTS_URL below if you ever
// change the font set. Commits both the woff2 files and the rewritten
// stylesheet so the site can serve them as static assets.
//
// Output: public/fonts/<hashed-name>.woff2 + public/fonts/fonts.css

import { writeFile, mkdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fontsDir = join(__dirname, "..", "public", "fonts");

const FONTS_URL =
  "https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap";

// Pretend to be a modern Chrome so Google serves woff2 + variable-font URLs.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36";

console.log(`Fetching CSS: ${FONTS_URL}`);
const cssResp = await fetch(FONTS_URL, { headers: { "User-Agent": UA } });
if (!cssResp.ok) throw new Error(`CSS fetch failed: ${cssResp.status}`);
const css = await cssResp.text();

// Pull every gstatic woff2 URL out of the CSS.
const urls = Array.from(
  new Set(css.match(/https:\/\/fonts\.gstatic\.com\/[^)]+\.woff2/g) ?? []),
);
console.log(`Found ${urls.length} woff2 subsets to download`);

await rm(fontsDir, { recursive: true, force: true });
await mkdir(fontsDir, { recursive: true });

const map = {};
let bytes = 0;
for (const url of urls) {
  const filename = basename(url);
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`woff2 fetch failed (${url}): ${resp.status}`);
  const buf = Buffer.from(await resp.arrayBuffer());
  await writeFile(join(fontsDir, filename), buf);
  map[url] = `/fonts/${filename}`;
  bytes += buf.length;
  console.log(`  ${filename} (${buf.length} bytes)`);
}

let rewritten =
  "/* Self-hosted Google Fonts. Generated by scripts/download-fonts.mjs.\n" +
  "   Do not edit by hand — re-run the script to refresh. */\n\n" +
  css;
for (const [from, to] of Object.entries(map)) {
  rewritten = rewritten.split(from).join(to);
}

await writeFile(join(fontsDir, "fonts.css"), rewritten);
console.log(
  `Wrote ${urls.length} woff2 files (${(bytes / 1024).toFixed(1)} KiB total) + fonts.css`,
);
