name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      # Step 3: Configure AWS credentials with OIDC
      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::653344975538:role/GitHubActionsRole
          aws-region: us-east-1

      # Step 4: Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 5: Run Tests
      - name: Run Tests
        run: npm test

      # Step 6: Build Project
      - name: Build Project
        run: npm run build

      # Step 7: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 8: Terraform Init
      - name: Terraform Init
        working-directory: infra/states/pablofallas.name
        run: terraform init

       # Step 9: Terraform Plan (Only on Pull Requests)
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: infra/states/pablofallas.name
        run: terraform plan

      # Step 10: Terraform Apply (Only on Push to Main)
      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: infra/states/pablofallas.name
        run: terraform apply -auto-approve
      
      # Step 11: Sync to S3 (Only on Push to Main)
      - name: Sync to S3
        if: github.event_name == 'push'
        run: |
          aws s3 sync build/ s3://pablofallas.name
